
name: sae
#name: Structure by Architecture

version: 0.1
license: MIT

#related: [foundation]

#description: "Universal configuration system for common execution environments"

src: startup.py

