
parents: [a/e/ladder/_ladder]

info.enc_type: l12

model.encoder:
  tfms: 12

  layers:
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
      down: 2
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
      down: 2
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
      down: 2
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
    - _type: <>rung_type
      net: <!>rung_net

    - _type: <>conv_type
      down: 2
    - _type: <>rung_type
      net: <!>rung_net
