
parents: [a/_base]

model.encoder:
  _type: ladder-enc

  _dout: None

  last: None

  rung_type: rung-infer

  style-dim:
    _type: expr
    _op: '//'
    _terms: [ <>latent-dim, <>tfms ]

  rung_net._type: mlp

  pool-rung: max

