
parents: ['t/3ds']

#floor_hue 10
#wall_hue 10
#object_hue 10
#scale 8
#shape 4
#orientation 15

dataset:

  folds:
    train:
      4: [0, 1]
    upd:
      4: [2]

  mix:
    train: 1



