parents: ['a/e/attn']

model:

    num_groups: 16

    head_dim: 2

    encoder:
        pointnet:
            pool:
                _type: 'multihead'

                heads:
                  _type: iter

                  _elements:
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp
                    - _type: mlp

info:
    arch_type: 'attn16'

