parents: ['a/d/prebranch']

model:

    branch_dim: 1

    decoder:
        _type: 'branch-dec'

        channels: [128,128,128, 128,128,128, 128,128,128, 128,128,128]
        factors: [1,1,2, 1,2,1, 2,1,2, 1,2,1]

        branches:
            _type: 'iter'

            _elements:
                - _type: '<>branch_type'
                - _type: '<>branch_type'
                - _type: '<>branch_type'

                - _type: '<>branch_type'
                - _type: '<>branch_type'
                - _type: '<>branch_type'

                - _type: '<>branch_type'
                - _type: '<>branch_type'
                - _type: '<>branch_type'

                - _type: '<>branch_type'
                - _type: '<>branch_type'
                - _type: '<>branch_type'

        layers:
            _type: 'iter'

            _elements:
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'

                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'

                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'

                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  output_nonlin: '<>nonlin'
                - _type: '<>layer_type'
                  norm: none



info:
    arch_type: 'deep-branch12'


