parents: ['basics']

model:



  decoder:
    _type: 'deconv'

    out_shape: '<>dout'

    channels: [128, 64, 64, 32, 32]
    kernels: 3
    factors: 2
    strides: 1

    up: 'bilinear'

    fc_hidden: [128, 256]

    output_nonlin: sigmoid

