parents: ['basics']

model:



  decoder:
    _type: 'deconv'

    out_shape: '<>dout'

    channels: [256, 256, 128, 128, 128, 128, 128, 128, 64, 64]
    kernels: 3
    factors: 2
    strides: [2,1, 2,1, 2,1, 2,1, 2,1]

    residual: True

    up: 'bilinear'

    fc_hidden: [128, 128, 256, 512]

    output_nonlin: sigmoid

