parents: [origin]

run:
  _type: sae-run
  _mod.timed-run: 1

#name: test-learn_rep

device: cuda
seed: 0
num_workers: 0

budget: 100000

time_limit: 4 # hrs

validation.freq: 10000
checkpoint.freq: 10000
print.freq: 100
viz.freq: 1000
records.freq: 200

fid._type: fid

dataset:
  device: cpu
  drop_last: yes


latent-dim: 12
