parents: [origin]

run:
  _type: sae-run
  _mod.timed-run: 1

#name: test-learn_rep

device: cuda
seed: 0
num_workers: 0

budget: 100000

time_limit: 4 # hrs

validation.freq: 10000
checkpoint.freq: 10000
print.freq: 100
viz.freq: 1000
records.freq: 200

fid._type: fid

dataset:
  device: cpu
  drop_last: yes


latent-dim: 12

model:
  _model_type: ae

  conv_type: conv-layer

  nonlin: elu
  norm: group

  reg: pow2

  criterion:
    _type: criterion
    ident: bce
    kwargs.reduction: sum

  optim:
    _type: adam
    lr: 0.0005
    weight_decay: 0
    momentum: 0
    beta1: 0.9
    beta2: 0.999

info:
  model_type: ae
