
parents: ['origin']

run:
  _mod: [cls-run, timed-run]

device: cuda
seed: 0
num_workers: 0

output:
  save_freq: 5000

  print_freq: 100
  log_freq: 200

  tensorboard: true

eval:
  compute_gt_fid: True

training:

  track_best: True

  no_test: True

  step_limit: 100000

  val_freq: 5000

  time_limit: 4 # hrs

dataset:
  drop_last: True
  device: cpu

model:
    _type: model
    _model_type: 'ae'

#    scheduler_type: 'step'
#    scheduler_step: 20000
#    scheduler_decay: .2
#    scheduler_min_lr: 1.e-6
#    scheduler_patience: 7

#    nonlin: 'elu'

#    viz_gen: True

    latent_dim: 12

    reg: pow2

    criterion: 'bce'

    norm: 'group'

    nonlin: 'elu'

#    encoder:
#      _type: 'dislib-enc'
#
#    decoder:
#      _type: 'dislib-dec'

    optim_type: 'adam'
    lr: 5.e-4
    weight_decay: 0
    momentum: 0
    beta1: 0.9
    beta2: 0.999

info:
    model_type: 'ae'

