parents: ['basics']

output:
    print_freq: 400
    save_freq: 10000

training:
    step_limit: 200000

dataset:
    name: 'celeba'

    batch_size: 32

    val_split: 0.1

model:
    latent_dim: 32

info:
    dataset_type: 'celeba'


