
_meta.script_name: train
#_meta.script_name: eval
#_meta.script_name: load-model

#parents: [hybrid, a/e/pretrained, a/d/conv, m/ae, d/3ds]
#parents: [extra/angle, hybrid, a/conv, m/vae, d/3ds]
#parents: [ hybrid, a/conv, m/vae, extra/angle ]
parents: [ hybrid, a/conv, m/vae, d/cppn ]

#ident: ese_vovnet39b_evos

dataset.num: 200

#latent-dim: 24
#reg-wt: 4

#model.optim:
#  lr: 0.001
#  _type: rmsprop
#  weight_decay: 0.0001
#  momentum: 0.9
#parents: [hybrid, a/e/conv12, a/d/strc/2, m/vae, d/3ds]
#parents: [demo]

#parents: [hybrid, a/e/conv12, a/d/strc/12, m/ae, d/scm]
#budget: 10
#dataset.net: None

#seed: 1000
#load: scm_ae_e-c12_d-s12_210210-044938
#parents: [eval/scm]
#run-name: scm_ae_e-c12_d-s12_210210-044938
#run-name: sim_vae1_e-c12_d-c12_210126-035851
#force-run: True
#
#figure_dir: 'C:\Users\anwan\OneDrive\Khan\research\learn_rep\figures\icml\scm'
#saveroot: C:\Users\anwan\Documents\workspace\sae\trained_nets


#parents: [ coord, nosplit, hybrid, a/e/conv12, a/d/strc/12, m/vae, d/3ds]
#parents: [ hybrid, a/e/conv12, a/d/strc/6, m/ae, d/3ds ]
#parents: [ hybrid, a/ladder/12, m/vae, d/mpi ]
#parents: [ hybrid, a/e/conv12, a/d/strc/2, m/vae, d/3ds ]
#parents: [ hybrid, a/conv12, m/wae, d/3ds ]

#parents: [ hybrid, a/e/conv16, a/d/strc/16, m/vae, d/celeba ]

#run-name: 3ds_ae0_e-c12_d-s4_nosplit_210125-045440
#run-name: toy_ae_e-c12_d-s12_mish-seed2_210126-122537
#path: 3ds_ae0_e-c12_d-s4_nosplit_210125-045440
#path: real_vae1_e-l2_d-l2_210127-231833
#

##override.mode: test
#mode: test
#mode: val
#ident: eval2
#ident: final-test2
#evaluation: None
#evaluation.step-limit: 10

#model.nonlin: mish
#model.norm: None
#model.residual: True
#reg-wt: 4
cat: toy

#latent-dim: 24

#dataset.name: random-scm
#dataset.device: cuda

#path: test-pycharm_210123-231915
#
#override:
#  eval:
#    mode: test
#    ident: final4
#
#  evaluation: None

#reg-wt: 16

#model.encoder.layers.0._type: coord-conv-layer

#budget: 1000
#viz.freq: 5

#evaluation: None
#validation: None

#eval.mode: test


#residual: yes

#reg-wt: 10000


#device: cuda

#model.optim.lr: 0.001


name: test-pycharm
inline: True
#device: cuda:1

#fid.dim: 2048
#fid.dim: 64
#fid.n_samples: 1000
#fid.batch_size: 20

#dataset:
#  device: cpu
#  category: real

pbar._type: progress-bar

print_dims: True



#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/wae, d/3ds ]
#parents: [hybrid, a/dislib, m/vae, d/3ds]
#parents: [scheduler, hybrid, a/d/new/12, a/e/conv, m/ae, d/3ds]

#parents: [hybrid, a/lconv, m/ae, d/mpi]
#parents: [ nosplit, hybrid, a/large/e/lconv, a/large/d/old16, m/vae, d/celeba ]
#parents: [a/ladder/12, m/vae, d/3ds]

#parents: [a/large/d/old16, a/large/e/conv, m/ae, d/celeba]
