
_meta.script_name: train
#_meta.script_name: eval

#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/wae, d/3ds ]
#parents: [hybrid, a/dislib, m/vae, d/3ds]
parents: [scheduler, hybrid, a/d/new/12, a/e/conv, m/ae, d/3ds]
#parents: [a/ladder/12, m/vae, d/3ds]

#parents: [a/large/d/old16, a/large/e/conv, m/ae, d/celeba]

#latent-dim: 24

#path: test-pycharm_210123-231915
#
#override:
#  eval:
#    mode: test
#    ident: final4
#
#  evaluation: None

#reg-wt: 16

#model.encoder.layers.0._type: coord-conv-layer

#budget: 1000
#viz.freq: 5

#evaluation: None
#validation: None

#eval.mode: test


#residual: yes



#device: cuda

#model.optim.lr: 0.001


name: test-pycharm
inline: True
#device: cuda:1

fid.dim: 64
fid.n_samples: 1000

#dataset:
#  device: cpu
#  category: real



print_dims: True



