
_meta.script_name: train
#_meta.script_name: eval

#parents: [ coord, nosplit, hybrid, a/e/conv12, a/d/strc/12, m/vae, d/3ds]
#parents: [ hybrid, a/e/conv12, a/d/strc/6, m/ae, d/3ds ]
#parents: [ hybrid, a/ladder/12, m/vae, d/mpi ]
#parents: [ hybrid, a/e/conv12, a/d/strc/2, m/vae, d/3ds ]
parents: [ hybrid, a/conv12, m/wae, d/3ds ]

#parents: [ hybrid, a/e/conv16, a/d/strc/16, m/ae, d/celeba ]

#model.nonlin: mish
#model.norm: None
#model.residual: True
#reg-wt: 4
#cat: sim

#latent-dim: 24

#path: test-pycharm_210123-231915
#
#override:
#  eval:
#    mode: test
#    ident: final4
#
#  evaluation: None

#reg-wt: 16

#model.encoder.layers.0._type: coord-conv-layer

#budget: 1000
#viz.freq: 5

#evaluation: None
#validation: None

#eval.mode: test


#residual: yes

#reg-wt: 10000


#device: cuda

#model.optim.lr: 0.001


#name: test-pycharm
inline: True
#device: cuda:1

fid.dim: 64
fid.n_samples: 1000

#dataset:
#  device: cpu
#  category: real



print_dims: True



#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/vae, d/3ds ]
#parents: [ a/conv, m/wae, d/3ds ]
#parents: [hybrid, a/dislib, m/vae, d/3ds]
#parents: [scheduler, hybrid, a/d/new/12, a/e/conv, m/ae, d/3ds]

#parents: [hybrid, a/lconv, m/ae, d/mpi]
#parents: [ nosplit, hybrid, a/large/e/lconv, a/large/d/old16, m/vae, d/celeba ]
#parents: [a/ladder/12, m/vae, d/3ds]

#parents: [a/large/d/old16, a/large/e/conv, m/ae, d/celeba]
