parents: ['base']

output:
    save_freq: 10000

    print_freq: 50

dataset:
    name: 'mnist'

    download: False

    labeled: True

    batch_size: 512

    val_split: 0.166666

training:
    step_limit: 10000

    val_freq: 1000

model:
    _type: 'model'

    nonlin: 'relu'

    net:
        _type: 'mlp'
        hidden_dims: [300]


    optim_type: 'adam'
    lr: 1.e-3
    weight_decay: 1.e-4
    momentum: 0
    beta1: 0.9
    beta2: 0.999


