
parents: ['base']

device: cuda
seed: 0
num_workers: 0

auto_name: True

output:
  save_freq: 5000

  print_freq: 200

training:

  track_best: True

  no_test: True

  step_limit: 150000

  val_freq: 5000

  time_limit: 2 # hrs

#  sample_limit: 100000000


model:
    _type: 'wpp'

    scheduler_type: 'step'
    scheduler_step: 20
    scheduler_decay: .2
    scheduler_min_lr: 1.e-6
    scheduler_patience: 7

    nonlin: 'prelu'

    viz_force_gen: True

    fc: [256, 128]

    channels: [32, 32, 64, 64, 128]
    kernels: 3
    factors: 1
    strides: 2

    downsampling: 'max'

    latent_dim: 12

    criterion:
        name: 'bce'
        reduction: 'sum'

    latent_reg_wt: 100
    gan_reg_wt: 10

    disc_steps: 5

    gan_wt: 1.e-4

    generator:
        _type: 'deconv'
        fc: [128, 128, 128, 256]

        channels: [128, 64, 64, 32, 32]
        factors: 2
        strides: 1

        upsampling: 'bilinear'

        output_nonlin: sigmoid

    discriminator:
        _type: 'conv'

        fc: [256, 128, 64]
        latent_dim: 1

#        lr: 5.e-3
        beta1: 0.5
        beta2: 0.9

    encoder:
        _type: 'conv'


    optim_type: 'adam'
    lr: 1.e-3
    weight_decay: 0
    momentum: 0
    beta1: 0.9
    beta2: 0.999

info:
    model_type: 'wpp'

