parents: ['basics']

model:

    encoder:
        _type: 'point-enc'

        transform:
            _type: 'patch-points'

        pointnet:
            _type: 'point-net'

            modules:
                _type: 'iter'

                _elements:
                    - _type: 'point-self'
                      output_nonlin: '<>nonlin'
                      hidden: [64, 128, 256]
                      pout: 512

            pool:
                _type: 'pool-points'
                fn: 'max'

            final:
                _type: 'mlp'
                hidden_dims: [256, 128]


info:
    arch_type: 'pointenc'


