parents: ['branchdec', 'basics']

model:

    key_dim: 32
    val_dim: 64
    keys_per_head: 3
    weight_keys: False
    gumbel: 0


    num_groups: 4

    branch_dim: 3

    encoder:
        _type: 'point-enc'

        transform:
            _type: 'patch-points'
            include_coords: True

        pointnet:
            _type: 'point-net'

            modules:
                _type: 'iter'

                _elements:
                    - _type: 'point-self'
                      #output_nonlin: '<>nonlin'
                      hidden: [128, 128, 128, 128, 128]
                      pout: '<>key_dim'

                    - _type: 'point-buffer'
                      channels: '<>val_dim'
                    - _type: 'point-wsum'
                      heads: '<>keys_per_head' # per group
                      groups: '<>num_groups'
#                      gumbel: 10
                      norm_heads: '<>weight_keys'
                    - _type: 'point-self'
                      output_nonlin: 'none'
                      hidden: [128, 128]
                      pout: '<>branch_dim'

            pool:
                _type: 'concat-points'

info:
    arch_type: 'pointenc-attn'


