parents: ['pointenc', 'branchdec', '3dshapes', 'basics']

inline: True

#training:
#  step_limit: 50000
#  val_freq: 1000
#
dataset:
  device: cpu
#  batch_size: 128

model:
  nonlin: mish


#resume = 'test-pycharm_191121-154737'
#
#extend = 7