
#parents: ['m/ae', 'a/d/branch-deep', 'a/conv', '3dshapes']

#parents: ['a/dislib', 'm/ae', '3dshapes']
#parents: ['a/d/deconv-deep', 'a/conv', 'm/ae', '3dshapes']

#parents: ['a/d/root6', 'a/e/conv', 'm/ae', '3dshapes']
parents: ['a/d/branch12', 'a/e/conv', 'm/ae', '3dshapes']

#parents: ['a/e/attn12', 'a/d/deconv', 'm/ae', '3dshapes']

#parents: ['a/e/attn12', 'a/d/branch12', 'm/ae', '3dshapes']


#parents: ['sup-3ds']

#resume: 3ds-ae-12b1-deep_0010-6241682-08_200414-021349

#override:
#  dataset:
#    device: cpu

#load: 'test-cmd_200412-140222'

#override:
#  training:
#    step_limit: 25000
#  eval:
#    identifier: test
#  dataset:
#    name: 3dshapes
#    _mod: __x__

inline: True

#device: "cuda:1"

#test_mode: 0

#eval:
#  n_samples: 500

#training:
#  step_limit: 1000
#  val_freq: 500
#
dataset:
  device: cpu
#  batch_size: 128
  category: real

#resume: vae_3ds_elu_d24_200320-040612\checkpoint_75000.pth.tar
#override:
#  inline: False
#  device: cuda:0
#  model:
#    min_log_std: -5

model:
  viz_gen: True
#  nonlin: relu

#  norm: 'instance'
  residual: True
  norm: None

#  keys_per_head: 4

#  coord_patches: 0

#  scheduler_type: 'cos'
#  scheduler_max_steps: 40
#  scheduler_min_lr: 1.e-5

#  optim_type: adamw
#  beta1: 0.90

#  min_log_std: -4

#  init_imp_mu: 1

#  imp_noise: 0.5



#  key_dim: 3
#  val_dim: 8
#  keys_per_head: 8
#  weight_keys: True
#  gumbel: 0

#  key_dim: 4
#  val_dim: 4
#  keys_per_head: 2

#  num_groups: 4
#  branch_dim: 3

#  decoder:
#    layer_type: 'double-deconv-layer'


#resume = 'test-pycharm_191121-154737'
#
#extend = 7