
parents: ['3dshapes']

dataset:
  labeled: True

model:
  _type: sup-model

  net:
    _type: conv

    latent_dim: '<>dout'

    channels: [32, 32, 64, 64, 128]
    fc: [256, 128]

    kernels: 3
    factors: 1
    strides: 2

    norm_type: group
    downsampling: max

  criterion:
    _type: multigroup-cls
    group_sizes: [10, 10, 10, 8, 4, 15]


