parents: [a/e/conv]

model.encoder:

  first.channels: 64

  layers:
    - _type: <>conv_type
      channels: 64
    - _type: <>conv_type
      channels: 64
      down: 1
    - _type: <>conv_type
      channels: 128
    - _type: <>conv_type
      channels: 128
      down: 1
    - _type: <>conv_type
      channels: 128
    - _type: <>conv_type
      channels: 128
      down: 1
    - _type: <>conv_type
      channels: 128
    - _type: <>conv_type
      channels: 256
      down: 1
    - _type: <>conv_type
      channels: 256


  last.hidden: [512, 256, 256, 128]