

#n_samples: 15120
#batch_size: 60

#num_steps: 5

fid-dim: 2048

tasks.interpolation:
  _type: task/interpolation/ps

#  interpolator: None

  encoder: <>model
  decoder: <>model

  criterion: rmse


