parents: [a/d/new/_style]


model.decoder:
  depth: 12

  up: 2

  layers:
    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net

    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net

    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net

    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net

    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>style_type
      net: <!>style_net