
parents: ['t/3ds']

#floor_hue 10
#wall_hue 10
#object_hue 10
#scale 8
#shape 4
#orientation 15

train_limit: 10000
update_limit: 10000

dataset:

  folds:
    train:
      4: [0, 1]
    upd:
      4: [2]
    test:
      4: [3]

  mix:
    train: 1

  limits:
    train: '<>train_limit'
    upd: '<>update_limit'


info:
  dataset_type: 't3ds-shapes'

