parents: ['basics']

model:

#    key_dim: 32
    val_dim: 64
    key_val_dim: 96

    keys_per_head: 3
    weight_keys: False

    gumbel: 0

#    num_groups: 4

#    branch_dim: 3

    encoder:
        _type: 'point-enc'

        transform:
            _type: 'patch-points'
            include_coords: True

        pointnet:
            _type: 'point-net'

            modules:
                _type: 'iter'

                _elements:
                    - _type: 'point-self'
                      #output_nonlin: '<>nonlin'
                      hidden: [128, 128, 128, 128, 128]
                      pout: '<>key_val_dim' # '<>key_dim'

#                    - _type: 'point-buffer'
#                      channels: '<>val_dim'

                    - _type: point-split
                      split: '<>val_dim'

                    - _type: 'point-wsum'
                      keys: '<>keys_per_head' # per group
                      heads: '<>num_groups'
#                      gumbel: 10
                      norm_heads: '<>weight_keys'
#                    - _type: 'point-self'
#                      output_nonlin: 'none'
#                      hidden: [128, 128]
#                      pout: '<>branch_dim'

            pool:
#                _type: 'concat-points'
                _type: 'multihead'

                head_douts: '<>branch_dim'

                heads:
                  _type: iter

                  hidden_dims: [128, 128]

#                  _elements: # missing

info:
    arch_type: 'pointenc-attn'


