
model:

    encoder:
        _type: 'conv'

        in_shape: '<>din'

        channels: [32, 32, 64, 64, 128]
        kernels: 3
        factors: 1
        strides: 2

        down: 'max'

        fc_hidden: [256, 128]



