
parents: [a/_base]

info.enc_type: c12

model.encoder:

  layers:
    - _type: <>conv_type
    - _type: <>conv_type
    - _type: <>conv_type
      down: 2
    
    - _type: <>conv_type
    - _type: <>conv_type
    - _type: <>conv_type
      down: 2
    
    - _type: <>conv_type
    - _type: <>conv_type
    - _type: <>conv_type
      down: 2
    
    - _type: <>conv_type
    - _type: <>conv_type
      down: 2



