parents: ['a/e/preladder']

model:

    rung_dims: 2

    encoder:

        rungs:
            _type: 'iter'

            _elements:
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 16, 8]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [16, 8]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 16]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 16]

                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 16]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 16]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128, 64]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128, 64]

                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128, 64]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128, 64]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]

                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]

        layers:

          channels: [32,32,32,32, 32,32,64,64, 64,64,64,64, 128,128,128,128]
          strides: [2,2,2,1, 1,1,2,1, 1,1,2,1, 1,1,1,1]

info:
    arch_type: 'dladder16'


