parents: ['a/e/preladder']

model:

    rung_dims: 3

    encoder:

        rungs:
            _type: 'iter'

            _elements:
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [16, 8]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [32, 64]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [64]
                - _type: '<>rung_type'
                  in_shape: '<>din'
                  latent_dim: '<>dout'
                  channels: [128]

        layers:

            channels: [32, 64, 64, 128]
            strides: 2


info:
    arch_type: 'ladder4'


