parents: ['basics']


model:

    encoder:
        _type: 'conv'

        in_shape: '<>din'

        channels: [64, 64, 128, 128, 128, 128, 128, 128, 256, 256]
        kernels: 3
        factors: [1,2, 1,2, 1,2, 1,2, 1,2]
        strides: 1

        residual: True

        down: 'max'

        fc_hidden: [512, 256, 256, 128]



