


model:

  rung_dims: 3
  residual_core: False




  encoder:
    _type: 'ladder-enc'

    rung_type: 'conv'

    layer_key: 'conv'

    kernels: 3
    factors: 2
    strides: 1

    down: 'max'

    rungs:
      _type: 'iter'


      channels: [64]

      fc_hidden: [64, 32]

    layers:
      _type: 'conv'

      in_shape: '<>din'
      residual: '<>residual_core'
