
_meta.script_name: eval-multiple-runs

pbar._type: progress-bar
mode: eval
save-ident: metrics
log-stats: yes

runs:
- 3ds_ae0_e-c12_d-c12_mish_210125-050038
- 3ds_vae1_e-c12_d-c12_mish_210125-140254
- 3ds_vae2_e-c12_d-c12_mish_210125-140255
- 3ds_wae10_e-c12_d-c12_mish_210125-140253
- 3ds_wae100_e-c12_d-c12_mish_210125-221143
- 3ds_wae1000_e-c12_d-c12_mish_210125-221142
- 3ds_ae0_e-c12_d-s4_mish_210125-140253
- 3ds_ae0_e-c12_d-s6_mish_210125-140253
- 3ds_ae0_e-c12_d-s12_mish_210125-050335
- 3ds_vae1_e-l4_d-l4_mish_210125-134914
- 3ds_vae1_e-l6_d-l6_mish_210125-140021
- 3ds_vae1_e-l12_d-l12_mish_210125-140249

#num_groups: 10
#num_latent: 100
#num_train: 100
#num_test: 100


override.model._print_model: False

dataset:
  _type: dataset
  _dataset_mod.joint-sampler: None
  name: 3dshapes
  mode: full
  labeled: True
  to_numpy: True

metrics._list:
  - _type: metric/irs
  - _type: metric/fairness
  - _type: metric/unsupervised
  - _type: metric/modularity-explicitness
  - _type: metric/sap
  - _type: metric/mig
  - _type: metric/dci
#  - _type: metric/factor-vae
#  - _type: metric/beta-vae
  - _type: metric/responses

