
_meta.script_name: eval-multiple-metrics

pbar._type: progress-bar
mode: eval
save-ident: metrics
log-stats: yes


saveroot: C:\Users\anwan\Documents\workspace\sae\trained_nets

#num_groups: 10
#num_latent: 100
#num_train: 100
#num_test: 100



override.model._print_model: False

dataset:
  _type: dataset
  _dataset_mod.joint-sampler: None
  name: celeba
  label_type: attr
  batch_size: 32

num_latent: 1000

metrics._list:
#  - _type: metric/irs
#  - _type: metric/fairness
#  - _type: metric/unsupervised
#  - _type: metric/modularity-explicitness
#  - _type: metric/sap
#  - _type: metric/mig
#  - _type: metric/dci
#  - _type: metric/factor-vae
#  - _type: metric/beta-vae
  - _type: metric/responses

