
_meta.script_name: eval-multiple-metrics

parents: [eval/_metrics]

#num_groups: 40

dataset:
  _type: dataset
  _dataset_mod.joint-sampler: None
#  name: full-mpi3d
  name: mpi3d
  mode: full
  labeled: True
  to_numpy: True
