parents: [base128, a/size/64]

batch-size: 32

dataset:
    _dataset_mod: interpolated

    size: 64

    name: 'celeba'

    batch_size: <>batch-size

    split.val: 0.1


info:
    dataset_type: celeba


