parents: [a/size/vec, base]

dataset:
  name: random-net

  batch_size: 128
  split.val: 0.1

  num-samples: 100000

  num-nodes: 8
  out-dim: 100

  nonlin: mish
  net:
    _type: mlp
    din: <>num-nodes
    dout: <>out-dim
    hidden: [128,128,128]

force-viz: True
fid: None

info:
  dataset_type: vec

