
parents: [a/d/old/_style]

model.decoder:
  depth: 6

  up: 2

  layers:
    - _type: <>style_type
      net: <!>style_net
    - _type: <>conv_type
      up: 1
#      channels: 128

    - _type: <>style_type
      net: <!>style_net
    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
    - _type: <>conv_type
#      up: 1

    - _type: <>style_type
      net: <!>style_net
    - _type: <>conv_type

    - _type: <>style_type
      net: <!>style_net
#    - _type: <>conv_type
#      channels: 32

  last.up: 1
