
parents: [base]

model.decoder:
  _type: style-dec

  final_din: None
  final_dout: <>dout

  # for conv layers
  channels: 64
  unpool: bilinear

  last:
    _type: <>conv_type
    nonlin: sigmoid
    norm: None

  # for style layers
  split-style: yes

  style_type: affine-adain

  style_net:
    _type: mlp
    hidden: [64, 128]

