
parents: [base]

model.decoder:
  _type: style-dec

  _din: None
  _dout: <>dout

  style-dim:
    _type: expr
    _op: '//'
    _terms: [<>latent-dim, <>depth]

  # for conv layers
  channels: 64
  unpool: bilinear

  last:
    _type: <>conv_type
    nonlin: sigmoid
    norm: None

  # for style layers
  split-style: yes
  normalize-features: no

  style_type: affine-adain

  style_net:
    _type: mlp
    hidden: [64, 128]

